name: "discord-notify"
on:
  workflow_run:
    workflows: [publish]
    types:
      - completed

jobs:
  notify-discord:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.0.6

      - name: Discord notification
        env:
          DISCORD_USERNAME: "Subspace Desktop Releases"
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_AVATAR: https://drive.google.com/drive/folders/1J0GtLE-6vTn7fpo9k3SrSy2TRL5isRH1
        uses: Ilshidur/action-discord@master
        with:
          args: "Subspace Desktop [${{ steps.extract_version.outputs.version}}](https://github.com/subspace/subspace-desktop/releases/tag/${{ steps.extract_version.outputs.version}}) has been released! Check it out on the [releases page](https://github.com/subspace/subspace-desktop/releases)."
